### ISSUE TITLE
undefined symbol: _ZTI5Shape

### ISSUE THREAD

**Issue by spmp** [notspiff/visualization.projectm#19]
Been trying for a while to get project-m working on Ubuntu 17.10 for a while, eventually built Kodi from git/master and rebuilt this repo as per instructions except that it is installed to `/usr`

Still get this error:
```
ERROR: Unable to load /usr/share/kodi/addons/visualization.projectm/visualization.projectm.so.2.0.0, reason: /usr/share/kodi/addons/visualization.projectm/visualization.projectm.so.2.0.0: undefined symbol: _ZTI5Shape
```

Project-m is not installed on the target system.

Any ideas how to solve this?

Cheers

**Comment by notspiff** [comment]
I fixed it 2 days ago...

Den søn. 15. jul. 2018, 10:45 skrev Jasper Aorangi <notifications@github.com

**Comment by spmp** [comment]
So you did, my bad for not `pull`ing 8)
 I am building to install in `/usr` as:
```
cmake -DADDONS_TO_BUILD=visualization.projectm -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
```
I had to copy `./install/visualization.projectm` to `/usr/share/kodi/addons/`

Now when I play audio with project-m visualisation Kodi restarts with:
```
20:00:27.760 T:140442125702592   ERROR: CSetting: missing <control> tag of "last_preset_folder"
20:00:27.761 T:140442125702592 WARNING: CSettingGroup: unable to read setting "last_preset_folder"
20:00:27.761 T:140442125702592   ERROR: CSetting: missing <control> tag of "last_preset_idx"
20:00:27.761 T:140442125702592 WARNING: CSettingGroup: unable to read setting "last_preset_idx"
20:00:27.761 T:140442125702592   ERROR: CSetting: missing <control> tag of "last_locked_status"
20:00:27.761 T:140442125702592 WARNING: CSettingGroup: unable to read setting "last_locked_status"
20:00:27.761 T:140442125702592   ERROR: kodi::General::get_setting_int - can't find setting 'last_preset_idx' in 'projectM'
20:00:27.761 T:140442125702592   ERROR: CSetting: missing <control> tag of "last_preset_folder"
20:00:27.761 T:140442125702592 WARNING: CSettingGroup: unable to read setting "last_preset_folder"
20:00:27.761 T:140442125702592   ERROR: CSetting: missing <control> tag of "last_preset_idx"
20:00:27.761 T:140442125702592 WARNING: CSettingGroup: unable to read setting "last_preset_idx"
```

Any ideas? feels close tho eh 8)

**Comment by notspiff** [comment]
don't pass PACKAGE_ZIP if you want to install into a unix-style prefix.

**Comment by spmp** [comment]
If I configure as you say:
```
cmake -DADDONS_TO_BUILD=visualization.projectm -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DPACKAGE_ZIP=0 ../../xbmc/cmake/addons
```
and `make sudo-install`
then libraries are installed into `/usr/lib/kodi/addons/visualisation.projectm`

When I try visualisation I get the following in the kodi log, but kodi does not crash:
```
19:26:30.286 T:139662903514560   ERROR: ADDON: Could not locate visualization.projectm.so.2.0.0
19:26:30.286 T:139662903514560   ERROR: IAddonInstanceHandler::CreateInstance: visualization.projectm returned bad status "Permanent failure" during instance creation
19:26:30.286 T:139662903514560   FATAL: Visualization: failed to create instance for 'visualization.projectm' and not usable!
```

If I copy the `.so` files to `/usr/share/kodi/addons/visualisation.projectm/` then I get the same error as in the previous message and kodi crashes/restarts

I have tried removing the local settings folder for `visualisation.projectm` it makes not difference.

**Comment by notspiff** [comment]
well, i dunno why your linker fails to find the so file, but that's how it is supposed to be laid out. /usr/share is mounted noexec on hardened  machines and is not meant for executable files.

**Comment by spmp** [comment]
Is there any extra logging or something that could help get to the bottom of this?
