### ISSUE TITLE
Preset change at the moment only possible without threading!

### ISSUE THREAD

**Issue by AlwinEsch** [notspiff/visualization.projectm#37]
Currently, ProjectM has a bug within the preset change, when a separate thread is used and Kodi then freezes.

Think it depends on the performance, on weaker system it worked for me but not on my strongest.

Error is reported here: https://github.com/projectM-visualizer/projectm/issues/243

To avoid this, the thread support is currently deactivated, see: https://github.com/xbmc/visualization.projectm/commit/386be2ea8ccb85be5ed0ccb90442b7756355d5ea#diff-610d6e017c2ffd2797e22ea52131ef84

Unfortunately, when a preset change occurs, sometimes a short white screen appears, because creating it is not complete.

Hope this thing gets fixed quickly.

**Comment by revmischa** [comment]
This issue should be fixed in master and 3.1.1-rc7 now in projectM - see https://github.com/projectM-visualizer/projectm/pull/276 and https://github.com/projectM-visualizer/projectm/issues/243
Please let us know if this fixes this issue (and maybe #29 ?)

**Comment by AlwinEsch** [comment]
Have checked it has worked with newest ProjectM version and becomes updated here https://github.com/xbmc/visualization.projectm/pull/41

Thanks a lot for the fix!
